//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfileServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws-infile.octtopro.com/", ConfigurationName="InfileServiceReference.WsINFILESoap")]
    public interface WsINFILESoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento param del espacio de nombres https://ws-infile.octtopro.com/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-infile.octtopro.com/GetJSONToRequireInvoice", ReplyAction="*")]
        InfileServiceReference.GetJSONToRequireInvoiceResponse GetJSONToRequireInvoice(InfileServiceReference.GetJSONToRequireInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-infile.octtopro.com/GetJSONToRequireInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<InfileServiceReference.GetJSONToRequireInvoiceResponse> GetJSONToRequireInvoiceAsync(InfileServiceReference.GetJSONToRequireInvoiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento param del espacio de nombres https://ws-infile.octtopro.com/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-infile.octtopro.com/GenerateInvoice", ReplyAction="*")]
        InfileServiceReference.GenerateInvoiceResponse GenerateInvoice(InfileServiceReference.GenerateInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-infile.octtopro.com/GenerateInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<InfileServiceReference.GenerateInvoiceResponse> GenerateInvoiceAsync(InfileServiceReference.GenerateInvoiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJSONToRequireInvoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJSONToRequireInvoice", Namespace="https://ws-infile.octtopro.com/", Order=0)]
        public InfileServiceReference.GetJSONToRequireInvoiceRequestBody Body;
        
        public GetJSONToRequireInvoiceRequest()
        {
        }
        
        public GetJSONToRequireInvoiceRequest(InfileServiceReference.GetJSONToRequireInvoiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws-infile.octtopro.com/")]
    public partial class GetJSONToRequireInvoiceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public GetJSONToRequireInvoiceRequestBody()
        {
        }
        
        public GetJSONToRequireInvoiceRequestBody(string param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJSONToRequireInvoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJSONToRequireInvoiceResponse", Namespace="https://ws-infile.octtopro.com/", Order=0)]
        public InfileServiceReference.GetJSONToRequireInvoiceResponseBody Body;
        
        public GetJSONToRequireInvoiceResponse()
        {
        }
        
        public GetJSONToRequireInvoiceResponse(InfileServiceReference.GetJSONToRequireInvoiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws-infile.octtopro.com/")]
    public partial class GetJSONToRequireInvoiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetJSONToRequireInvoiceResult;
        
        public GetJSONToRequireInvoiceResponseBody()
        {
        }
        
        public GetJSONToRequireInvoiceResponseBody(string GetJSONToRequireInvoiceResult)
        {
            this.GetJSONToRequireInvoiceResult = GetJSONToRequireInvoiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateInvoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateInvoice", Namespace="https://ws-infile.octtopro.com/", Order=0)]
        public InfileServiceReference.GenerateInvoiceRequestBody Body;
        
        public GenerateInvoiceRequest()
        {
        }
        
        public GenerateInvoiceRequest(InfileServiceReference.GenerateInvoiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws-infile.octtopro.com/")]
    public partial class GenerateInvoiceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public GenerateInvoiceRequestBody()
        {
        }
        
        public GenerateInvoiceRequestBody(string param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateInvoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateInvoiceResponse", Namespace="https://ws-infile.octtopro.com/", Order=0)]
        public InfileServiceReference.GenerateInvoiceResponseBody Body;
        
        public GenerateInvoiceResponse()
        {
        }
        
        public GenerateInvoiceResponse(InfileServiceReference.GenerateInvoiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws-infile.octtopro.com/")]
    public partial class GenerateInvoiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateInvoiceResult;
        
        public GenerateInvoiceResponseBody()
        {
        }
        
        public GenerateInvoiceResponseBody(string GenerateInvoiceResult)
        {
            this.GenerateInvoiceResult = GenerateInvoiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WsINFILESoapChannel : InfileServiceReference.WsINFILESoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WsINFILESoapClient : System.ServiceModel.ClientBase<InfileServiceReference.WsINFILESoap>, InfileServiceReference.WsINFILESoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsINFILESoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WsINFILESoapClient.GetBindingForEndpoint(endpointConfiguration), WsINFILESoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsINFILESoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsINFILESoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsINFILESoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsINFILESoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsINFILESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InfileServiceReference.GetJSONToRequireInvoiceResponse InfileServiceReference.WsINFILESoap.GetJSONToRequireInvoice(InfileServiceReference.GetJSONToRequireInvoiceRequest request)
        {
            return base.Channel.GetJSONToRequireInvoice(request);
        }
        
        public string GetJSONToRequireInvoice(string param)
        {
            InfileServiceReference.GetJSONToRequireInvoiceRequest inValue = new InfileServiceReference.GetJSONToRequireInvoiceRequest();
            inValue.Body = new InfileServiceReference.GetJSONToRequireInvoiceRequestBody();
            inValue.Body.param = param;
            InfileServiceReference.GetJSONToRequireInvoiceResponse retVal = ((InfileServiceReference.WsINFILESoap)(this)).GetJSONToRequireInvoice(inValue);
            return retVal.Body.GetJSONToRequireInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InfileServiceReference.GetJSONToRequireInvoiceResponse> InfileServiceReference.WsINFILESoap.GetJSONToRequireInvoiceAsync(InfileServiceReference.GetJSONToRequireInvoiceRequest request)
        {
            return base.Channel.GetJSONToRequireInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<InfileServiceReference.GetJSONToRequireInvoiceResponse> GetJSONToRequireInvoiceAsync(string param)
        {
            InfileServiceReference.GetJSONToRequireInvoiceRequest inValue = new InfileServiceReference.GetJSONToRequireInvoiceRequest();
            inValue.Body = new InfileServiceReference.GetJSONToRequireInvoiceRequestBody();
            inValue.Body.param = param;
            return ((InfileServiceReference.WsINFILESoap)(this)).GetJSONToRequireInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InfileServiceReference.GenerateInvoiceResponse InfileServiceReference.WsINFILESoap.GenerateInvoice(InfileServiceReference.GenerateInvoiceRequest request)
        {
            return base.Channel.GenerateInvoice(request);
        }
        
        public string GenerateInvoice(string param)
        {
            InfileServiceReference.GenerateInvoiceRequest inValue = new InfileServiceReference.GenerateInvoiceRequest();
            inValue.Body = new InfileServiceReference.GenerateInvoiceRequestBody();
            inValue.Body.param = param;
            InfileServiceReference.GenerateInvoiceResponse retVal = ((InfileServiceReference.WsINFILESoap)(this)).GenerateInvoice(inValue);
            return retVal.Body.GenerateInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InfileServiceReference.GenerateInvoiceResponse> InfileServiceReference.WsINFILESoap.GenerateInvoiceAsync(InfileServiceReference.GenerateInvoiceRequest request)
        {
            return base.Channel.GenerateInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<InfileServiceReference.GenerateInvoiceResponse> GenerateInvoiceAsync(string param)
        {
            InfileServiceReference.GenerateInvoiceRequest inValue = new InfileServiceReference.GenerateInvoiceRequest();
            inValue.Body = new InfileServiceReference.GenerateInvoiceRequestBody();
            inValue.Body.param = param;
            return ((InfileServiceReference.WsINFILESoap)(this)).GenerateInvoiceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsINFILESoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WsINFILESoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsINFILESoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ws-infile.octtopro.com/WsINFILE.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WsINFILESoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ws-infile.octtopro.com/WsINFILE.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WsINFILESoap,
            
            WsINFILESoap12,
        }
    }
}
